[package]
name = "advent_of_code_2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug = true

[dependencies]
regex = "1"
fancy-regex = "0.12.0"
itertools = "0.12"
rayon = "1.8"
num = "0.4"